# Generated by Django 4.0.4 on 2022-05-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='products',
            field=models.ManyToManyField(null=True, to='mainpage.product', verbose_name='choose the products'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='products_subtitle',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='products section description // subtitle'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='products_title',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='products section title'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='projects',
            field=models.ManyToManyField(null=True, to='mainpage.project', verbose_name='chosse the projects'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='projects_subtitle',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='projects section description // subtitle'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='projects_title',
            field=models.CharField(default='Projetos', max_length=155, null=True, verbose_name='projects section title'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='services',
            field=models.ManyToManyField(null=True, to='mainpage.service', verbose_name='choose a service'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='services_subtitle',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='services section description // subtitle'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='services_title',
            field=models.CharField(default='serviços', max_length=155, null=True, verbose_name='servies section title'),
        ),
    ]
