# Generated by Django 4.0.4 on 2022-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_aboutme_avatar_alter_mainpage_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Main page?'),
        ),
    ]
